/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateMemeRequest = IDL.Record({
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
});
export const Meme = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMeme' : IDL.Func([CreateMemeRequest], [IDL.Nat], []),
  'deleteMeme' : IDL.Func([IDL.Nat], [], []),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMemeById' : IDL.Func([IDL.Nat], [IDL.Opt(Meme)], ['query']),
  'getMemeCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMemes' : IDL.Func([], [IDL.Vec(Meme)], ['query']),
  'getMemesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Meme)], ['query']),
  'getMostLikedMemes' : IDL.Func([IDL.Nat], [IDL.Vec(Meme)], ['query']),
  'getTotalLikes' : IDL.Func([], [IDL.Nat], ['query']),
  'getTrendingTags' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getUserMemeCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTotalLikes' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'hasLikedMeme' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleLikeMeme' : IDL.Func([IDL.Nat], [], []),
  'upsertUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateMemeRequest = IDL.Record({
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'username' : IDL.Text });
  const Meme = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMeme' : IDL.Func([CreateMemeRequest], [IDL.Nat], []),
    'deleteMeme' : IDL.Func([IDL.Nat], [], []),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMemeById' : IDL.Func([IDL.Nat], [IDL.Opt(Meme)], ['query']),
    'getMemeCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMemes' : IDL.Func([], [IDL.Vec(Meme)], ['query']),
    'getMemesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Meme)], ['query']),
    'getMostLikedMemes' : IDL.Func([IDL.Nat], [IDL.Vec(Meme)], ['query']),
    'getTotalLikes' : IDL.Func([], [IDL.Nat], ['query']),
    'getTrendingTags' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
    'getUserMemeCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTotalLikes' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'hasLikedMeme' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleLikeMeme' : IDL.Func([IDL.Nat], [], []),
    'upsertUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };