/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateMemeRequest {
  'title' : string,
  'blob' : ExternalBlob,
  'tags' : Array<string>,
  'authorName' : string,
}
export type ExternalBlob = Uint8Array;
export interface Meme {
  'id' : bigint,
  'title' : string,
  'blob' : ExternalBlob,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'authorName' : string,
  'author' : Principal,
  'likes' : bigint,
}
export interface UserProfile { 'bio' : string, 'username' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMeme' : ActorMethod<[CreateMemeRequest], bigint>,
  'deleteMeme' : ActorMethod<[bigint], undefined>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMemeById' : ActorMethod<[bigint], [] | [Meme]>,
  'getMemeCount' : ActorMethod<[], bigint>,
  'getMemes' : ActorMethod<[], Array<Meme>>,
  'getMemesByUser' : ActorMethod<[Principal], Array<Meme>>,
  'getMostLikedMemes' : ActorMethod<[bigint], Array<Meme>>,
  'getTotalLikes' : ActorMethod<[], bigint>,
  'getTrendingTags' : ActorMethod<[bigint], Array<string>>,
  'getUserMemeCount' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTotalLikes' : ActorMethod<[Principal], bigint>,
  'hasLikedMeme' : ActorMethod<[bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleLikeMeme' : ActorMethod<[bigint], undefined>,
  'upsertUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];